### PR TITLE
[FEATURE] Changed Accordion panel label to panel title (was id)

### PR DESCRIPTION
**Pull request by boettner-it**

### CODE REVIEW

**Comment by misterboe** [comment]
the title could not be set by itteration, because the the panel is now identified by a unique hash. if you change the sorting and use a label wich only count the panels it would not fit

**Comment by boettner-it** [comment]
For me sorting works with the proposed change. How does the label affect sorting? From a users perspective naming the panels with hashes is not very convenient. At least some of my customers editors complained... :-)

**Comment by apiening** [comment]
I can confirm that the proposed change does not conflict with the ordering of the tabs. At least not in my tests. For me it is out of question that displaying the magical number of the panel id in the backend is not a good idea: The content editors need to know the panel titles in order to be able to place their content correctly.
Is there anything that holds back this pull request?

**Comment by dahaupt** [comment]
@Outdoorsman Can we get this in, please? 🚀

**Pull request merged**
