### PR TITLE
Remove executable bit on files

### PR DESCRIPTION
**Pull request by PowerKiKi**
Remove permission to execute files for all files.

### CODE REVIEW

**Comment by xf-** [comment]
Please rebase ;)

**Comment by PowerKiKi** [comment]
rebased

Just in case, you can easily reproduce that patch with:

```
find . -type f -exec chmod a-x {} \;
```

**Comment by xf-** [comment]
i prefer ;)
find -type f | xargs chmod 644
i didn't want to "steal" the PR

Last thing - Please prefix the Commit
[BUGFIX]

**Comment by PowerKiKi** [comment]
done :)

**Pull request merged**
